#### first create  the folder 
## mkdir -p /opt/appdata/ouroboros
## mkdir -p /opt/appdata/ouroboros/hooks
## chown -cR 1000:1000 /opt/appdata/ouroboros 
## chmod -cR 755 /opt/appdata/ouroboros 
---
version: '3'
services:
  ouroboros:
    container_name: ouroboros
    hostname: ouroboros
    image: gmt2001/ouroboros
    environment:
      - CLEANUP=true
      - INTERVAL=300
      - LOG_LEVEL=info
      - SELF_UPDATE=true
      - LATEST=true
      - IGNORE=mongo influxdb postgres mariadb
      - TZ=America/New_York
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/appdata/ouroboros/hooks:/opt/appdata/ouroboros/hooks
